name: "Godot test"
on: push

env:
  GODOT_VERSION: 4.2.1
  PROJECT_PATH: src

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Test
        run: |
          cd $PROJECT_PATH
          godot --headless --verbose -d -s --path . ./addons/gut/gut_cmdln.gd -gdir ./test/unit/ -gexit

